FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app

COPY . .

RUN dotnet restore "PortraitFr.API.csproj"
RUN dotnet build "PortraitFr.API.csproj" -c Release

# Installe dotnet-ef
RUN dotnet tool install --global dotnet-ef --version 9.0.3

# Chemin vers dotnet tools
ENV PATH="${PATH}:/root/.dotnet/tools"

# Applique les migrations
CMD ["dotnet", "ef", "database", "update"]

