version: '3.8'

services:
  portraitfr_frontend:
    build: ./Frontend/portraitfr-frontend
    container_name: portraitfr_frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"  # Port standard Next.js
    volumes:
      - ./Frontend/portraitfr-frontend:/app
      - /app/node_modules
    networks:
      - portraitfr-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  portraitfr-net:
    driver: bridge