version: '3.8'

services:
  portraitfr_db:
    image: postgres:16
    container_name: portraitfr_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - portraitfr_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - portraitfr-net

  portraitfr_backend:
    build: ./Backend/PortraitFr.API
    container_name: portraitfr_backend
    depends_on:
      - portraitfr_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=portraitfr_db;Database=portraitfr;Username=postgres;Password=password
    ports:
      - "5010:80"
    volumes:
      - ./Backend/PortraitFr.API/wwwroot/photos:/app/wwwroot/photos
    networks:
      - portraitfr-net

  portraitfr_frontend:
    build: ./Frontend/portraitfr-frontend
    container_name: portraitfr_frontend
    ports:
      - "5011:3000"
    networks:
      - portraitfr-net

  portraitfr_migration:
    build:
      context: ./Backend/PortraitFr.API
      dockerfile: Dockerfile.migration
    container_name: portraitfr_migration
    depends_on:
      - portraitfr_db
    working_dir: /app
    environment:
      - ConnectionStrings__DefaultConnection=Host=portraitfr_db;Database=portraitfr;Username=postgres;Password=password
    networks:
      - portraitfr-net

  portraitfr_pgadmin:
    image: dpage/pgadmin4
    container_name: portraitfr_pgadmin
    depends_on:
      - portraitfr_db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@portraitfr.fr
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - portraitfr-net

volumes:
  portraitfr_data:
    name: portraitfr_data

networks:
  portraitfr-net:
    driver: bridge
